@startuml
class Fournisseur {
	**id : int**
	nom : string
	email : string
	telephone : string
	<color:#0000dd>categories : Categorie[]</color>
}

class Categorie {
	**id : int**
	nom : string
	image : string
	<color:#0000dd>parent : Categorie</color>
	<color:#0000dd>enfants : Categorie[]</color>
	<color:#0000dd>fournisseurs : Fournisseur[]</color>
}

Fournisseur "*"--"*" Categorie
Categorie "*"--"1" Categorie


hide methods

hide circle

@enduml
